ktor {
  deployment {
    port = 8080
    host = "0.0.0.0"
  }

  application {
    modules = [ org.psei.ApplicationKt.module ]
  }
}

# Database settings (example)
database {
  jdbcUrl = "jdbc:postgresql://localhost:5432/psei"
  user = "psei_user"
  password = "change-me"
}
